[[node]]
id="cache"
value="Cache"

[[node]]
id="alu"
value="ALU"
pivot="top"
base=["cache","bottom"]
xy=[0,35]

[[node]]
id="cu"
value="Řídící\njednotka"
pivot="top"
base=["alu","bottom"]
xy=[0,35]

[[node]]
id="datareg"
value="Datové\nregistry"
pivot="left"
base=["alu","right"]
xy=[35,0]

[[node]]
id="statusreg"
value="Stavové\nregistry"
pivot="left"
base=["cu","right"]
xy=[35,0]
