[variables]
bg_width = 1000
bg_height = 140
node_height = 70
node_bg_offset = 35
space = 25
dia_w = 160
dia_h = 100

[node.bg_bg]
z = 2
size = [1002, 420]

[node.bg_z]
z = 3
value = "Zákazník"
size = ["bg_width", "bg_height"]
label_pos = "top-left"
xy = ["bg_bg", "top-left", 1, 1]
color = "#ffffffff"
color_border = "#00000000"
label_shift = [-10, -10]

[node.bg_p]
z = 3
value = "Pracovník"
size = ["bg_width", "bg_height"]
label_pos = "top-left"
pivot = "top"
xy = ["bg_z", "bottom", 0, -1]
color = "#f8f8f8ff"
color_border = "#00000000"
label_shift = [-10, -10]

[node.bg_s]
z = 3
value = "Systém"
size = ["bg_width", "bg_height"]
label_pos = "top-left"
pivot = "top"
xy = ["bg_p", "bottom", 0, -1]
color = "#f0f0f0ff"
color_border = "#00000000"
label_shift = [-10, -10]

[node.z_0]
size = [0, "node_height"]
type = "ellipse"
value = "Zahájení\npoptávky"
xy = ["bg_z", "top-left", 75, "node_bg_offset"]

[node.z_1]
size = [0, "node_height"]
value = "Kontaktuje\npodnik"
pivot = "left"
xy = ["z_0", "right", "space", 0]

[[path]]
start = ["z_0", "right", 0, 0]
end = ["z_1", "left", 0, 0]

[node.p_0]
size = [0, "node_height"]
value = "Zahájí\nzpracování\nobjednávky"
xy = ["bg_p", "top-left", 110, "node_bg_offset"]

[[path]]
start = ["z_1", "bottom", 0, 0]
end = ["p_0", "top", 0, 0]
shift = 20

[node.s_0]
size = ["dia_w", "dia_h"]
label_shift = [6, 0]
type = "diamond"
value = "Existuje\nzákaznický\núčet?"
xy = ["bg_s", "top-left", 93, 15]

[[path]]
start = ["p_0", "bottom", 0, 0]
end = ["s_0", "top", 0, 0]

[node.p_1]
size = [0, "node_height"]
value = "Vytvoří\nzákaznický\núčet v systému"
xy = ["p_0", "top-right", 75, 0]

[node.p_2]
size = [0, "node_height"]
value = "Zadá parametry\npoptávaných\nproduktů"
xy = ["p_1", "top-right", "space", 0]

[[path]]
start = ["s_0", "right", 0, 0]
end = ["p_1", "left", 0, 0]
points = [["", "start", 0, "", "end", 0]]
shift = 7

[[path]]
start = ["s_0", "bottom", 0, 0]
end = ["p_2", "bottom", 0, 0]
points = [
    ["s_0", "right", 30, "", "prev", 0],
    ["", "prev", 0, "", "end", 0]
]
shift = 15

[node.s_1]
size = ["dia_w", "dia_h"]
label_shift = [12, 0]
type = "diamond"
value = "Existuje\nodpovídající\nprodukt?"
xy = ["s_0", "top-right", 35, 0]

[node.s_2]
size = [0, "node_height"]
value = "Automaticky\nvytvoří\nprodukt"
pivot = "left"
xy = ["s_1", "right", "space", 0]
